'use strict';
const fs = require('fs');
const file = 'src-admin/src/components/tabs/LongtermTrendsView.tsx';
let c = fs.readFileSync(file, 'utf8');

// Locate old drift mini-chart block
const startIdx = c.indexOf('{/* 6.', c.indexOf('DRIFT-MONITOR') - 50);
const endMarker = '</Grid>\r\n                    </Grid>\r\n                </>';
const endMarkerLF = '</Grid>\n                    </Grid>\n                </>';
let endIdx = c.indexOf(endMarker, startIdx);
let eLen = endMarker.length;
if (endIdx < 0) { endIdx = c.indexOf(endMarkerLF, startIdx); eLen = endMarkerLF.length; }

if (startIdx < 0 || endIdx < 0) {
    console.error('Block not found. startIdx=' + startIdx + ' endIdx=' + endIdx);
    process.exit(1);
}

console.log('Replacing block:', startIdx, '->', endIdx + eLen, '(' + (endIdx + eLen - startIdx) + ' chars)');

const newBlock = [
    '{/* DRIFT-MONITOR vollbreite Karte */}',
    '                    </Grid>',
    '                    {/* ═══ DRIFT-MONITOR ═══ */}',
    '                    <Grid item xs={12}>',
    '                        <Paper sx={{ p: 2, bgcolor: isDark ? \'#0a0a0a\' : \'#ffffff\', border: `1px solid ${isDark ? \'#333\' : \'#ddd\'}` }}>',
    '                            <Box sx={{ display: \'flex\', alignItems: \'center\', justifyContent: \'space-between\', mb: 1.5 }}>',
    '                                <Box sx={{ display: \'flex\', alignItems: \'center\', gap: 1 }}>',
    '                                    <Typography variant="subtitle2" sx={{ fontWeight: \'bold\', color: \'#ff9800\' }}>',
    '                                        \uD83D\uDD2C DRIFT-MONITOR',
    '                                    </Typography>',
    '                                    <ChartHelp text={"Erkennt schleichende Ver\u00e4nderungen \u00fcber Wochen und Monate (Page-Hinkley-Test). Anders als die t\u00e4gliche Anomalie-Erkennung sieht der Drift-Monitor kumulative Trends: Wenn die Aktivit\u00e4t langsam sinkt, die Ganggeschwindigkeit langsam steigt oder die Nacht-Unruhe zunimmt, schl\u00e4gt dieser Monitor an. Die ersten 7-14 Tage dienen der Kalibrierung."} />',
    '                                </Box>',
    '                                <Typography variant="caption" sx={{ color: \'text.secondary\', fontSize: \'0.6rem\' }}>',
    '                                    {driftData?.n_days ? `${driftData.n_days} Tage Datenbasis` : \'\'}',
    '                                </Typography>',
    '                            </Box>',
    '',
    '                            {driftLoading ? (',
    '                                <Typography variant="caption" sx={{ color: \'text.secondary\', display: \'block\', textAlign: \'center\', py: 2 }}>',
    '                                    Lade Drift-Daten (bis zu 180 Tage)\u2026',
    '                                </Typography>',
    '                            ) : driftData && !driftData.error ? (',
    '                                <>',
    '                                    {/* Status-Chips f\u00fcr alle 3 Metriken */}',
    '                                    <Box sx={{ display: \'flex\', gap: 1, flexWrap: \'wrap\', mb: 2 }}>',
    '                                        {[',
    '                                            { key: \'activity\', label: \'Aktivit\u00e4t\',          icon: \'\uD83C\uDFC3\', invert: true },',
    '                                            { key: \'gait\',     label: \'Ganggeschwindigkeit\', icon: \'\uD83D\uDEB6\', invert: false },',
    '                                            { key: \'night\',    label: \'Nacht-Unruhe\',        icon: \'\uD83D\uDE34\', invert: false },',
    '                                        ].map(({ key, label, icon }) => {',
    '                                            const m = (driftData as any)[key];',
    '                                            if (!m || m.error) return (',
    '                                                <Box key={key} sx={{ display: \'flex\', alignItems: \'center\', gap: 0.5, px: 1, py: 0.3, borderRadius: 1, bgcolor: isDark ? \'#1a1a1a\' : \'#f5f5f5\' }}>',
    '                                                    <Typography variant="caption" sx={{ color: \'text.secondary\', fontSize: \'0.65rem\' }}>{icon} {label}: {m?.error || \'Keine Daten\'}</Typography>',
    '                                                </Box>',
    '                                            );',
    '                                            const ratio = m.current_score / (m.threshold || 1);',
    '                                            const color = m.drift_detected ? \'#dc3545\' : ratio > 0.5 ? \'#fd7e14\' : \'#28a745\';',
    '                                            const status = m.drift_detected ? \'Drift erkannt\' : ratio > 0.5 ? \'Beobachten\' : \'Stabil\';',
    '                                            return (',
    '                                                <Box key={key} sx={{ display: \'flex\', alignItems: \'center\', gap: 0.5, px: 1.2, py: 0.4, borderRadius: 1, bgcolor: color + \'22\', border: `1px solid ${color}44` }}>',
    '                                                    <Box sx={{ width: 7, height: 7, borderRadius: \'50%\', bgcolor: color }} />',
    '                                                    <Typography variant="caption" sx={{ fontWeight: \'bold\', color, fontSize: \'0.7rem\' }}>',
    '                                                        {icon} {label}: {status}',
    '                                                    </Typography>',
    '                                                    <Typography variant="caption" sx={{ color: \'text.secondary\', fontSize: \'0.6rem\' }}>',
    '                                                        &nbsp;({m.current_score?.toFixed(1)} / {m.threshold?.toFixed(0)})',
    '                                                    </Typography>',
    '                                                </Box>',
    '                                            );',
    '                                        })}',
    '                                    </Box>',
    '',
    '                                    {/* 3-Kurven Chart */}',
    '                                    {(() => {',
    '                                        const maxLen = Math.max(',
    '                                            (driftData as any).activity?.scores?.length || 0,',
    '                                            (driftData as any).gait?.scores?.length     || 0,',
    '                                            (driftData as any).night?.scores?.length    || 0',
    '                                        );',
    '                                        if (maxLen === 0) return null;',
    '                                        const chartData = Array.from({ length: maxLen }, (_: any, i: number) => ({',
    '                                            i: i + 1,',
    '                                            act:   (driftData as any).activity?.scores?.[i] != null ? Math.round((driftData as any).activity.scores[i] * 10) / 10 : null,',
    '                                            gait:  (driftData as any).gait?.scores?.[i]     != null ? Math.round((driftData as any).gait.scores[i]     * 10) / 10 : null,',
    '                                            night: (driftData as any).night?.scores?.[i]    != null ? Math.round((driftData as any).night.scores[i]     * 10) / 10 : null,',
    '                                        }));',
    '                                        const maxThreshold = Math.max(',
    '                                            (driftData as any).activity?.threshold || 0,',
    '                                            (driftData as any).gait?.threshold     || 0,',
    '                                            (driftData as any).night?.threshold    || 0,',
    '                                        );',
    '                                        const maxScore = Math.max(',
    '                                            (driftData as any).activity?.current_score || 0,',
    '                                            (driftData as any).gait?.current_score     || 0,',
    '                                            (driftData as any).night?.current_score    || 0,',
    '                                        );',
    '                                        const yMax = Math.ceil(Math.max(maxThreshold, maxScore) * 1.2) || 50;',
    '                                        return (',
    '                                            <ResponsiveContainer width="100%" height={180}>',
    '                                                <LineChart data={chartData} margin={{ top: 5, right: 30, left: 0, bottom: 5 }}>',
    '                                                    <CartesianGrid strokeDasharray="2 4" stroke={isDark ? \'#222\' : \'#eee\'} />',
    '                                                    <XAxis dataKey="i" stroke={lineColor} style={{ fontSize: \'0.55rem\' }} />',
    '                                                    <YAxis stroke={lineColor} style={{ fontSize: \'0.55rem\' }} domain={[0, yMax]} />',
    '                                                    <Tooltip',
    '                                                        formatter={(v: any, name: string) => {',
    '                                                            const labels: Record<string,string> = { act: \'\uD83C\uDFC3 Aktivit\u00e4t\', gait: \'\uD83D\uDEB6 Ganggeschw.\', night: \'\uD83D\uDE34 Nacht\' };',
    '                                                            return [v != null ? `${v}` : \'\u2013\', labels[name] || name];',
    '                                                        }}',
    '                                                        contentStyle={{ backgroundColor: isDark ? \'#1a1a1a\' : \'#fff\', border: \'1px solid #444\', fontSize: \'0.7rem\' }}',
    '                                                    />',
    '                                                    <ReferenceLine y={maxThreshold} stroke="#dc3545" strokeDasharray="4 3"',
    '                                                        label={{ value: \'Alarm-Schwelle\', position: \'right\', fill: \'#dc3545\', fontSize: 9 }} />',
    '                                                    {(driftData as any).activity?.scores && <Line type="monotone" dataKey="act"   stroke="#4fc3f7" strokeWidth={1.5} dot={false} connectNulls name="act"   />}',
    '                                                    {(driftData as any).gait?.scores     && <Line type="monotone" dataKey="gait"  stroke="#ff9800" strokeWidth={1.5} dot={false} connectNulls name="gait"  />}',
    '                                                    {(driftData as any).night?.scores    && <Line type="monotone" dataKey="night" stroke="#ce93d8" strokeWidth={1.5} dot={false} connectNulls name="night" />}',
    '                                                </LineChart>',
    '                                            </ResponsiveContainer>',
    '                                        );',
    '                                    })()}',
    '',
    '                                    <Typography variant="caption" sx={{ color: \'text.secondary\', fontSize: \'0.6rem\', display: \'block\', mt: 1 }}>',
    '                                        \uD83D\uDD35 Aktivit\u00e4t\u00a0\u00b7\u00a0\uD83D\uDFE0 Ganggeschwindigkeit\u00a0\u00b7\u00a0\uD83D\uDFE3 Nacht-Unruhe\u00a0\u00a0|\u00a0\u00a0Anstieg = Verhaltensmuster \u00e4ndert sich. Rote Linie = Alarm-Schwelle.',
    '                                        {(driftData as any).activity?.calibration_days ? ` Erste ${(driftData as any).activity.calibration_days} Tage = Kalibrierung.` : \'\'}',
    '                                    </Typography>',
    '                                </>',
    '                            ) : driftData?.error ? (',
    '                                <Typography variant="caption" sx={{ color: \'text.secondary\', display: \'block\', fontSize: \'0.65rem\' }}>',
    '                                    {driftData.error}',
    '                                </Typography>',
    '                            ) : (',
    '                                <Typography variant="caption" sx={{ color: \'text.secondary\', display: \'block\', textAlign: \'center\', py: 2 }}>',
    '                                    Drift-Analyse l\u00e4dt\u2026 (min. 10 Tage Daten n\u00f6tig)',
    '                                </Typography>',
    '                            )}',
    '                        </Paper>',
    '                    </Grid>',
    '                    <Grid item xs={12} style={{ display: \'none\' }}>{/* keeps grid structure */}',
].join('\n');

const newContent = c.substring(0, startIdx) + newBlock + '\n                    </Grid>\n                </>' + c.substring(endIdx + eLen);
fs.writeFileSync(file, newContent, 'utf8');
console.log('Done! New length:', newContent.length);
